/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GameJob = { 'policeOfficer' : null } |
  { 'unemployed' : null } |
  { 'firstResponder' : null } |
  { 'swat' : null } |
  { 'dealershipWorker' : null };
export interface Home {
  'garageSpaces' : bigint,
  'customizationLevel' : bigint,
  'address' : string,
  'rooms' : bigint,
}
export type PlayerId = string;
export interface PlayerProfile {
  'id' : PlayerId,
  'name' : string,
  'homeOwnership' : [] | [Home],
  'avatarUrl' : [] | [string],
  'relationships' : Array<Relationship>,
  'currentJob' : GameJob,
}
export interface Relationship {
  'relationType' : { 'friend' : null } |
    { 'family' : null },
  'name' : string,
}
export interface Settings {
  'violenceToggle' : boolean,
  'chatEnabled' : boolean,
  'graphicsQuality' : { 'low' : null } |
    { 'high' : null } |
    { 'medium' : null },
  'cameraMode' : { 'firstPerson' : null } |
    { 'thirdPerson' : null },
  'controlScheme' : string,
}
export interface UserProfile {
  'name' : string,
  'homeOwnership' : [] | [Home],
  'avatarUrl' : [] | [string],
  'relationships' : Array<Relationship>,
  'currentJob' : GameJob,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFriend' : ActorMethod<[string], boolean>,
  'addRelationship' : ActorMethod<
    [string, { 'friend' : null } | { 'family' : null }],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProfile' : ActorMethod<[string, GameJob], [] | [PlayerProfile]>,
  'customizeHome' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFriendsList' : ActorMethod<[string], Array<string>>,
  'getProfile' : ActorMethod<[string], [] | [PlayerProfile]>,
  'getSearchableProfiles' : ActorMethod<[string], Array<PlayerProfile>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseHome' : ActorMethod<[string, bigint, bigint], undefined>,
  'removeFriend' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAvatar' : ActorMethod<[string], undefined>,
  'updateJob' : ActorMethod<[GameJob], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];