/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameJob = IDL.Variant({
  'policeOfficer' : IDL.Null,
  'unemployed' : IDL.Null,
  'firstResponder' : IDL.Null,
  'swat' : IDL.Null,
  'dealershipWorker' : IDL.Null,
});
export const PlayerId = IDL.Text;
export const Home = IDL.Record({
  'garageSpaces' : IDL.Nat,
  'customizationLevel' : IDL.Nat,
  'address' : IDL.Text,
  'rooms' : IDL.Nat,
});
export const Relationship = IDL.Record({
  'relationType' : IDL.Variant({ 'friend' : IDL.Null, 'family' : IDL.Null }),
  'name' : IDL.Text,
});
export const PlayerProfile = IDL.Record({
  'id' : PlayerId,
  'name' : IDL.Text,
  'homeOwnership' : IDL.Opt(Home),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'relationships' : IDL.Vec(Relationship),
  'currentJob' : GameJob,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'homeOwnership' : IDL.Opt(Home),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'relationships' : IDL.Vec(Relationship),
  'currentJob' : GameJob,
});
export const Settings = IDL.Record({
  'violenceToggle' : IDL.Bool,
  'chatEnabled' : IDL.Bool,
  'graphicsQuality' : IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  }),
  'cameraMode' : IDL.Variant({
    'firstPerson' : IDL.Null,
    'thirdPerson' : IDL.Null,
  }),
  'controlScheme' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFriend' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addRelationship' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'friend' : IDL.Null, 'family' : IDL.Null })],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProfile' : IDL.Func([IDL.Text, GameJob], [IDL.Opt(PlayerProfile)], []),
  'customizeHome' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFriendsList' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(PlayerProfile)], ['query']),
  'getSearchableProfiles' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PlayerProfile)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseHome' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'removeFriend' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAvatar' : IDL.Func([IDL.Text], [], []),
  'updateJob' : IDL.Func([GameJob], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameJob = IDL.Variant({
    'policeOfficer' : IDL.Null,
    'unemployed' : IDL.Null,
    'firstResponder' : IDL.Null,
    'swat' : IDL.Null,
    'dealershipWorker' : IDL.Null,
  });
  const PlayerId = IDL.Text;
  const Home = IDL.Record({
    'garageSpaces' : IDL.Nat,
    'customizationLevel' : IDL.Nat,
    'address' : IDL.Text,
    'rooms' : IDL.Nat,
  });
  const Relationship = IDL.Record({
    'relationType' : IDL.Variant({ 'friend' : IDL.Null, 'family' : IDL.Null }),
    'name' : IDL.Text,
  });
  const PlayerProfile = IDL.Record({
    'id' : PlayerId,
    'name' : IDL.Text,
    'homeOwnership' : IDL.Opt(Home),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'relationships' : IDL.Vec(Relationship),
    'currentJob' : GameJob,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'homeOwnership' : IDL.Opt(Home),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'relationships' : IDL.Vec(Relationship),
    'currentJob' : GameJob,
  });
  const Settings = IDL.Record({
    'violenceToggle' : IDL.Bool,
    'chatEnabled' : IDL.Bool,
    'graphicsQuality' : IDL.Variant({
      'low' : IDL.Null,
      'high' : IDL.Null,
      'medium' : IDL.Null,
    }),
    'cameraMode' : IDL.Variant({
      'firstPerson' : IDL.Null,
      'thirdPerson' : IDL.Null,
    }),
    'controlScheme' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFriend' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addRelationship' : IDL.Func(
        [IDL.Text, IDL.Variant({ 'friend' : IDL.Null, 'family' : IDL.Null })],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProfile' : IDL.Func(
        [IDL.Text, GameJob],
        [IDL.Opt(PlayerProfile)],
        [],
      ),
    'customizeHome' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFriendsList' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(PlayerProfile)], ['query']),
    'getSearchableProfiles' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PlayerProfile)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseHome' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'removeFriend' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAvatar' : IDL.Func([IDL.Text], [], []),
    'updateJob' : IDL.Func([GameJob], [], []),
    'updateSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };