/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Relationship {
    relationType: Variant_friend_family;
    name: string;
}
export interface Settings {
    violenceToggle: boolean;
    chatEnabled: boolean;
    graphicsQuality: Variant_low_high_medium;
    cameraMode: Variant_firstPerson_thirdPerson;
    controlScheme: string;
}
export type PlayerId = string;
export interface JobProgress {
    failedMissions: bigint;
    successfulMissions: bigint;
    roleSpecificStats: RoleSpecificStats;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PlayerProfile {
    id: PlayerId;
    name: string;
    homeOwnership?: Home;
    avatarUrl?: string;
    relationships: Array<Relationship>;
    currentJob: GameJob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type RoleSpecificStats = {
    __kind__: "policeOfficer";
    policeOfficer: {
        arrestsMade: bigint;
        finesIssued: bigint;
    };
} | {
    __kind__: "firstResponder";
    firstResponder: {
        rescuesPerformed: bigint;
        medicalAssists: bigint;
    };
} | {
    __kind__: "swat";
    swat: {
        operationsCompleted: bigint;
        hostageRescues: bigint;
    };
} | {
    __kind__: "dealershipWorker";
    dealershipWorker: {
        vehiclesSold: bigint;
    };
};
export interface Home {
    garageSpaces: bigint;
    customizationLevel: bigint;
    address: string;
    rooms: bigint;
}
export interface UserProfile {
    name: string;
    homeOwnership?: Home;
    avatarUrl?: string;
    relationships: Array<Relationship>;
    currentJob: GameJob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum GameJob {
    policeOfficer = "policeOfficer",
    unemployed = "unemployed",
    firstResponder = "firstResponder",
    swat = "swat",
    dealershipWorker = "dealershipWorker"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_firstPerson_thirdPerson {
    firstPerson = "firstPerson",
    thirdPerson = "thirdPerson"
}
export enum Variant_friend_family {
    friend = "friend",
    family = "family"
}
export enum Variant_low_high_medium {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFriend(friendId: string): Promise<boolean>;
    addRelationship(name: string, relationType: Variant_friend_family): Promise<void>;
    adminResetJobProgress(targetUser: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProfile(name: string, job: GameJob): Promise<PlayerProfile | null>;
    customizeHome(customizationLevel: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFriendsList(targetId: string): Promise<Array<string>>;
    /**
     * /   Role Progress   ///
     */
    getJobProgress(): Promise<JobProgress>;
    getProfile(targetId: string): Promise<PlayerProfile | null>;
    getSearchableProfiles(searchTerm: string): Promise<Array<PlayerProfile>>;
    getSettings(): Promise<Settings>;
    getUserJobProgress(user: Principal): Promise<JobProgress | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    purchaseHome(address: string, rooms: bigint, garageSpaces: bigint): Promise<void>;
    removeFriend(friendId: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setJobProgress(newProgress: JobProgress): Promise<void>;
    updateAvatar(avatarUrl: string): Promise<void>;
    updateJob(newJob: GameJob): Promise<void>;
    updateSettings(newSettings: Settings): Promise<void>;
}
import type { GameJob as _GameJob, Home as _Home, JobProgress as _JobProgress, PlayerId as _PlayerId, PlayerProfile as _PlayerProfile, Relationship as _Relationship, RoleSpecificStats as _RoleSpecificStats, Settings as _Settings, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFriend(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addFriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFriend(arg0);
            return result;
        }
    }
    async addRelationship(arg0: string, arg1: Variant_friend_family): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRelationship(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRelationship(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminResetJobProgress(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetJobProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetJobProgress(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProfile(arg0: string, arg1: GameJob): Promise<PlayerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, to_candid_GameJob_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, to_candid_GameJob_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async customizeHome(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.customizeHome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.customizeHome(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriendsList(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendsList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendsList(arg0);
            return result;
        }
    }
    async getJobProgress(): Promise<JobProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobProgress();
                return from_candid_JobProgress_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobProgress();
            return from_candid_JobProgress_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: string): Promise<PlayerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSearchableProfiles(arg0: string): Promise<Array<PlayerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSearchableProfiles(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSearchableProfiles(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_Settings_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_Settings_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserJobProgress(arg0: Principal): Promise<JobProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserJobProgress(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserJobProgress(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async purchaseHome(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseHome(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseHome(arg0, arg1, arg2);
            return result;
        }
    }
    async removeFriend(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFriend(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setJobProgress(arg0: JobProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setJobProgress(to_candid_JobProgress_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setJobProgress(to_candid_JobProgress_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAvatar(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAvatar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAvatar(arg0);
            return result;
        }
    }
    async updateJob(arg0: GameJob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(to_candid_GameJob_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(to_candid_GameJob_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(to_candid_Settings_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(to_candid_Settings_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_GameJob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameJob): GameJob {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_JobProgress_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobProgress): JobProgress {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerProfile): PlayerProfile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Relationship_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Relationship): Relationship {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RoleSpecificStats_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoleSpecificStats): RoleSpecificStats {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Settings_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Settings): Settings {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerProfile]): PlayerProfile | null {
    return value.length === 0 ? null : from_candid_PlayerProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Home]): Home | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobProgress]): JobProgress | null {
    return value.length === 0 ? null : from_candid_JobProgress_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlayerId;
    name: string;
    homeOwnership: [] | [_Home];
    avatarUrl: [] | [string];
    relationships: Array<_Relationship>;
    currentJob: _GameJob;
}): {
    id: PlayerId;
    name: string;
    homeOwnership?: Home;
    avatarUrl?: string;
    relationships: Array<Relationship>;
    currentJob: GameJob;
} {
    return {
        id: value.id,
        name: value.name,
        homeOwnership: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.homeOwnership)),
        avatarUrl: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.avatarUrl)),
        relationships: from_candid_vec_n18(_uploadFile, _downloadFile, value.relationships),
        currentJob: from_candid_GameJob_n22(_uploadFile, _downloadFile, value.currentJob)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    relationType: {
        friend: null;
    } | {
        family: null;
    };
    name: string;
}): {
    relationType: Variant_friend_family;
    name: string;
} {
    return {
        relationType: from_candid_variant_n21(_uploadFile, _downloadFile, value.relationType),
        name: value.name
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    homeOwnership: [] | [_Home];
    avatarUrl: [] | [string];
    relationships: Array<_Relationship>;
    currentJob: _GameJob;
}): {
    name: string;
    homeOwnership?: Home;
    avatarUrl?: string;
    relationships: Array<Relationship>;
    currentJob: GameJob;
} {
    return {
        name: value.name,
        homeOwnership: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.homeOwnership)),
        avatarUrl: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.avatarUrl)),
        relationships: from_candid_vec_n18(_uploadFile, _downloadFile, value.relationships),
        currentJob: from_candid_GameJob_n22(_uploadFile, _downloadFile, value.currentJob)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    failedMissions: bigint;
    successfulMissions: bigint;
    roleSpecificStats: _RoleSpecificStats;
}): {
    failedMissions: bigint;
    successfulMissions: bigint;
    roleSpecificStats: RoleSpecificStats;
} {
    return {
        failedMissions: value.failedMissions,
        successfulMissions: value.successfulMissions,
        roleSpecificStats: from_candid_RoleSpecificStats_n31(_uploadFile, _downloadFile, value.roleSpecificStats)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    violenceToggle: boolean;
    chatEnabled: boolean;
    graphicsQuality: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
    cameraMode: {
        firstPerson: null;
    } | {
        thirdPerson: null;
    };
    controlScheme: string;
}): {
    violenceToggle: boolean;
    chatEnabled: boolean;
    graphicsQuality: Variant_low_high_medium;
    cameraMode: Variant_firstPerson_thirdPerson;
    controlScheme: string;
} {
    return {
        violenceToggle: value.violenceToggle,
        chatEnabled: value.chatEnabled,
        graphicsQuality: from_candid_variant_n36(_uploadFile, _downloadFile, value.graphicsQuality),
        cameraMode: from_candid_variant_n37(_uploadFile, _downloadFile, value.cameraMode),
        controlScheme: value.controlScheme
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    friend: null;
} | {
    family: null;
}): Variant_friend_family {
    return "friend" in value ? Variant_friend_family.friend : "family" in value ? Variant_friend_family.family : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    policeOfficer: null;
} | {
    unemployed: null;
} | {
    firstResponder: null;
} | {
    swat: null;
} | {
    dealershipWorker: null;
}): GameJob {
    return "policeOfficer" in value ? GameJob.policeOfficer : "unemployed" in value ? GameJob.unemployed : "firstResponder" in value ? GameJob.firstResponder : "swat" in value ? GameJob.swat : "dealershipWorker" in value ? GameJob.dealershipWorker : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    policeOfficer: {
        arrestsMade: bigint;
        finesIssued: bigint;
    };
} | {
    firstResponder: {
        rescuesPerformed: bigint;
        medicalAssists: bigint;
    };
} | {
    swat: {
        operationsCompleted: bigint;
        hostageRescues: bigint;
    };
} | {
    dealershipWorker: {
        vehiclesSold: bigint;
    };
}): {
    __kind__: "policeOfficer";
    policeOfficer: {
        arrestsMade: bigint;
        finesIssued: bigint;
    };
} | {
    __kind__: "firstResponder";
    firstResponder: {
        rescuesPerformed: bigint;
        medicalAssists: bigint;
    };
} | {
    __kind__: "swat";
    swat: {
        operationsCompleted: bigint;
        hostageRescues: bigint;
    };
} | {
    __kind__: "dealershipWorker";
    dealershipWorker: {
        vehiclesSold: bigint;
    };
} {
    return "policeOfficer" in value ? {
        __kind__: "policeOfficer",
        policeOfficer: value.policeOfficer
    } : "firstResponder" in value ? {
        __kind__: "firstResponder",
        firstResponder: value.firstResponder
    } : "swat" in value ? {
        __kind__: "swat",
        swat: value.swat
    } : "dealershipWorker" in value ? {
        __kind__: "dealershipWorker",
        dealershipWorker: value.dealershipWorker
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Variant_low_high_medium {
    return "low" in value ? Variant_low_high_medium.low : "high" in value ? Variant_low_high_medium.high : "medium" in value ? Variant_low_high_medium.medium : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    firstPerson: null;
} | {
    thirdPerson: null;
}): Variant_firstPerson_thirdPerson {
    return "firstPerson" in value ? Variant_firstPerson_thirdPerson.firstPerson : "thirdPerson" in value ? Variant_firstPerson_thirdPerson.thirdPerson : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Relationship>): Array<Relationship> {
    return value.map((x)=>from_candid_Relationship_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerProfile>): Array<PlayerProfile> {
    return value.map((x)=>from_candid_PlayerProfile_n14(_uploadFile, _downloadFile, x));
}
function to_candid_GameJob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameJob): _GameJob {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_JobProgress_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobProgress): _JobProgress {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_Relationship_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Relationship): _Relationship {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_RoleSpecificStats_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoleSpecificStats): _RoleSpecificStats {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_Settings_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Settings): _Settings {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    homeOwnership?: Home;
    avatarUrl?: string;
    relationships: Array<Relationship>;
    currentJob: GameJob;
}): {
    name: string;
    homeOwnership: [] | [_Home];
    avatarUrl: [] | [string];
    relationships: Array<_Relationship>;
    currentJob: _GameJob;
} {
    return {
        name: value.name,
        homeOwnership: value.homeOwnership ? candid_some(value.homeOwnership) : candid_none(),
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        relationships: to_candid_vec_n41(_uploadFile, _downloadFile, value.relationships),
        currentJob: to_candid_GameJob_n11(_uploadFile, _downloadFile, value.currentJob)
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    relationType: Variant_friend_family;
    name: string;
}): {
    relationType: {
        friend: null;
    } | {
        family: null;
    };
    name: string;
} {
    return {
        relationType: to_candid_variant_n8(_uploadFile, _downloadFile, value.relationType),
        name: value.name
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    failedMissions: bigint;
    successfulMissions: bigint;
    roleSpecificStats: RoleSpecificStats;
}): {
    failedMissions: bigint;
    successfulMissions: bigint;
    roleSpecificStats: _RoleSpecificStats;
} {
    return {
        failedMissions: value.failedMissions,
        successfulMissions: value.successfulMissions,
        roleSpecificStats: to_candid_RoleSpecificStats_n46(_uploadFile, _downloadFile, value.roleSpecificStats)
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    violenceToggle: boolean;
    chatEnabled: boolean;
    graphicsQuality: Variant_low_high_medium;
    cameraMode: Variant_firstPerson_thirdPerson;
    controlScheme: string;
}): {
    violenceToggle: boolean;
    chatEnabled: boolean;
    graphicsQuality: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
    cameraMode: {
        firstPerson: null;
    } | {
        thirdPerson: null;
    };
    controlScheme: string;
} {
    return {
        violenceToggle: value.violenceToggle,
        chatEnabled: value.chatEnabled,
        graphicsQuality: to_candid_variant_n50(_uploadFile, _downloadFile, value.graphicsQuality),
        cameraMode: to_candid_variant_n51(_uploadFile, _downloadFile, value.cameraMode),
        controlScheme: value.controlScheme
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameJob): {
    policeOfficer: null;
} | {
    unemployed: null;
} | {
    firstResponder: null;
} | {
    swat: null;
} | {
    dealershipWorker: null;
} {
    return value == GameJob.policeOfficer ? {
        policeOfficer: null
    } : value == GameJob.unemployed ? {
        unemployed: null
    } : value == GameJob.firstResponder ? {
        firstResponder: null
    } : value == GameJob.swat ? {
        swat: null
    } : value == GameJob.dealershipWorker ? {
        dealershipWorker: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "policeOfficer";
    policeOfficer: {
        arrestsMade: bigint;
        finesIssued: bigint;
    };
} | {
    __kind__: "firstResponder";
    firstResponder: {
        rescuesPerformed: bigint;
        medicalAssists: bigint;
    };
} | {
    __kind__: "swat";
    swat: {
        operationsCompleted: bigint;
        hostageRescues: bigint;
    };
} | {
    __kind__: "dealershipWorker";
    dealershipWorker: {
        vehiclesSold: bigint;
    };
}): {
    policeOfficer: {
        arrestsMade: bigint;
        finesIssued: bigint;
    };
} | {
    firstResponder: {
        rescuesPerformed: bigint;
        medicalAssists: bigint;
    };
} | {
    swat: {
        operationsCompleted: bigint;
        hostageRescues: bigint;
    };
} | {
    dealershipWorker: {
        vehiclesSold: bigint;
    };
} {
    return value.__kind__ === "policeOfficer" ? {
        policeOfficer: value.policeOfficer
    } : value.__kind__ === "firstResponder" ? {
        firstResponder: value.firstResponder
    } : value.__kind__ === "swat" ? {
        swat: value.swat
    } : value.__kind__ === "dealershipWorker" ? {
        dealershipWorker: value.dealershipWorker
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_low_high_medium): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Variant_low_high_medium.low ? {
        low: null
    } : value == Variant_low_high_medium.high ? {
        high: null
    } : value == Variant_low_high_medium.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_firstPerson_thirdPerson): {
    firstPerson: null;
} | {
    thirdPerson: null;
} {
    return value == Variant_firstPerson_thirdPerson.firstPerson ? {
        firstPerson: null
    } : value == Variant_firstPerson_thirdPerson.thirdPerson ? {
        thirdPerson: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_friend_family): {
    friend: null;
} | {
    family: null;
} {
    return value == Variant_friend_family.friend ? {
        friend: null
    } : value == Variant_friend_family.family ? {
        family: null
    } : value;
}
function to_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Relationship>): Array<_Relationship> {
    return value.map((x)=>to_candid_Relationship_n42(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
